// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGUrLVev3eqURZ6mzJFmj042Ae_57JOTM',
    appId: '1:960963029347:web:847b25b6730430d4ef4b56',
    messagingSenderId: '960963029347',
    projectId: 'canary-ec729',
    authDomain: 'canary-ec729.firebaseapp.com',
    storageBucket: 'canary-ec729.appspot.com',
    measurementId: 'G-2L5SGS1FH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiO0pXdK--nOJyGPJ50o1qCnk_v_Pgzsc',
    appId: '1:960963029347:android:27c19108f57adc99ef4b56',
    messagingSenderId: '960963029347',
    projectId: 'canary-ec729',
    storageBucket: 'canary-ec729.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzf-9AIqZyzSYR9y80VryqZ5YQLmcJjkI',
    appId: '1:960963029347:ios:fcb5a061ba8c56e8ef4b56',
    messagingSenderId: '960963029347',
    projectId: 'canary-ec729',
    storageBucket: 'canary-ec729.appspot.com',
    iosClientId: '960963029347-114qvh2j1emghits4lf9io8dvtgsogqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.canary',
  );
}
